services:
    Playtini\EasyAdminHelperBundle\Dashboard\DashboardHelper:
        autowire: true
        public: true
    Playtini\EasyAdminHelperBundle\Dashboard\EasyAdminContext:
        autowire: true
        public: true
    Playtini\EasyAdminHelperBundle\Frontmatter\FrontmatterParser:
        autowire: true
        public: true

    Playtini\EasyAdminHelperBundle\Controller\:
        autowire: true
        autoconfigure: true
        public: true
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
